### ISSUE TITLE
About office hours

### ISSUE THREAD

**Issue by koichishi** [dilevin/CSC417-physics-based-animation#2]
Do we happen to have a discord channel for the office hours or we can just post them here?

**Comment by dilevin** [comment]
I was planning to do office hours via zoom but you can also post questions here if that is easier. 

If there's big demand for a Discord channel I'm happy to set one up.

**Comment by dilevin** [comment]
also, sorry this took. so long to reply to, I just didn't notice the notification, I'll do better as we go :)

**Comment by koichishi** [comment]
Thanks!
