### ISSUE TITLE
Request: Record chat content in lecture records

### ISSUE THREAD

**Issue by TRDizer** [dilevin/CSC417-physics-based-animation#5]
When watching the record of today's lecture, some of the questions are typed in chat, but since it is not included in the video record, responses towards those questions asked in chat seem a bit out of context (eg. 46:29 in record 9/16/2020, where clarifying the concept of virtual work in the scenario where the object of interest is leaning against a wall).

Not sure if people are concerned about having the conservation in chat being recorded, but if not, it would be greatly appreciated so that one may find it easier following discussion or Q&A.

**Comment by dilevin** [comment]
oh no problem, I can do that. I think it's already saved somewhere. I'll dig it up and add it.
